"""followers

Revision ID: 348ebac323ef
Revises: 820438b5301c
Create Date: 2020-02-04 11:03:39.744660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '348ebac323ef'
down_revision = '820438b5301c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
