"""new fields in user model

Revision ID: 820438b5301c
Revises: b00727e1a191
Create Date: 2020-02-01 10:14:44.985558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '820438b5301c'
down_revision = 'b00727e1a191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
